### PR TITLE
Fixes and upgrades

### PR DESCRIPTION
**Pull request by AmiterCodes**
Fixed typo, made code less repetitive, added more file extensions and also a torrents folder

### CODE REVIEW

**Comment by codeperfectplus** [comment]
@AmiterCodes Thanks for improving the functionality and clean code.

**Comment by codeperfectplus** [comment]
@AmiterCodes Thanks, But there was an error.
shutil has a function `move` and you created the same function with `move` so that's why the program crashed

```python
from shutil import move
def move(arr,name,ex,file):
    for i in range(len(arr)):
        if ex == arr[i]:
            move(file,name)
```
It was more like recursion.move function was calling `your function` not shutil function.

### Solution

```python
from shutil import move
def transfer(arr,name,ex,file):
    for i in range(len(arr)):
        if ex == arr[i]:
            move(file,name)
```


Happy Coding,

**Comment by AmiterCodes** [comment]
Oh I didn't realize that...

**Comment by codeperfectplus** [comment]
I fixed it.

**Pull request merged**
